#pragma once
#include "myTypes.h"

enum PedTypes
{
	PED_TYPE_PLAYER_0,	// michael
	PED_TYPE_PLAYER_1,	// franklin
	PED_TYPE_NETWORK_PLAYER,	// mp character
	PED_TYPE_PLAYER_2,	// trevor
	PED_TYPE_CIVMALE,
	PED_TYPE_CIVFEMALE,
	PED_TYPE_COP,
	PED_TYPE_GANG_ALBANIAN,
	PED_TYPE_GANG_BIKER_1,
	PED_TYPE_GANG_BIKER_2,
	PED_TYPE_GANG_ITALIAN,
	PED_TYPE_GANG_RUSSIAN,
	PED_TYPE_GANG_RUSSIAN_2,
	PED_TYPE_GANG_IRISH,
	PED_TYPE_GANG_JAMAICAN,
	PED_TYPE_GANG_AFRICAN_AMERICAN,
	PED_TYPE_GANG_KOREAN,
	PED_TYPE_GANG_CHINESE_JAPANESE,
	PED_TYPE_GANG_PUERTO_RICAN,
	PED_TYPE_DEALER,
	PED_TYPE_MEDIC,
	PED_TYPE_FIREMAN,
	PED_TYPE_CRIMINAL,
	PED_TYPE_BUM,
	PED_TYPE_PROSTITUTE,
	PED_TYPE_SPECIAL,
	PED_TYPE_MISSION,
	PED_TYPE_SWAT,
	PED_TYPE_ANIMAL,
	PED_TYPE_ARMY
};

enum InputGroups
{
	INPUTGROUP_MOVE = 0,
	INPUTGROUP_LOOK = 1,
	INPUTGROUP_WHEEL = 2,
	INPUTGROUP_CELLPHONE_NAVIGATE = 3,
	INPUTGROUP_CELLPHONE_NAVIGATE_UD = 4,
	INPUTGROUP_CELLPHONE_NAVIGATE_LR = 5,
	INPUTGROUP_FRONTEND_DPAD_ALL = 6,
	INPUTGROUP_FRONTEND_DPAD_UD = 7,
	INPUTGROUP_FRONTEND_DPAD_LR = 8,
	INPUTGROUP_FRONTEND_LSTICK_ALL = 9,
	INPUTGROUP_FRONTEND_RSTICK_ALL = 10,
	INPUTGROUP_FRONTEND_GENERIC_UD = 11,
	INPUTGROUP_FRONTEND_GENERIC_LR = 12,
	INPUTGROUP_FRONTEND_GENERIC_ALL = 13,
	INPUTGROUP_FRONTEND_BUMPERS = 14,
	INPUTGROUP_FRONTEND_TRIGGERS = 15,
	INPUTGROUP_FRONTEND_STICKS = 16,
	INPUTGROUP_SCRIPT_DPAD_ALL = 17,
	INPUTGROUP_SCRIPT_DPAD_UD = 18,
	INPUTGROUP_SCRIPT_DPAD_LR = 19,
	INPUTGROUP_SCRIPT_LSTICK_ALL = 20,
	INPUTGROUP_SCRIPT_RSTICK_ALL = 21,
	INPUTGROUP_SCRIPT_BUMPERS = 22,
	INPUTGROUP_SCRIPT_TRIGGERS = 23,
	INPUTGROUP_WEAPON_WHEEL_CYCLE = 24,
	INPUTGROUP_FLY = 25,
	INPUTGROUP_SUB = 26,
	INPUTGROUP_VEH_MOVE_ALL = 27,
	INPUTGROUP_CURSOR = 28,
	INPUTGROUP_CURSOR_SCROLL = 29,
	INPUTGROUP_SNIPER_ZOOM_SECONDARY = 30,
	INPUTGROUP_VEH_HYDRAULICS_CONTROL = 31,
	MAX_INPUTGROUPS = 32,
	INPUTGROUP_INVALID = 33
};

enum PedConfigFlags
{
	PED_FLAG_CAN_FLY_THRU_WINDSCREEN = 32,
	PED_FLAG_DIES_BY_RAGDOLL = 33,
	PED_FLAG_NO_COLLISION = 52,
	_PED_FLAG_IS_SHOOTING = 58,
	_PED_FLAG_IS_ON_GROUND = 60,
	PED_FLAG_NO_COLLIDE = 62,
	PED_FLAG_NO_JUMPING = 67,
	PED_FLAG_NO_SPEECH = 69,
	PED_WAS_KILLED_BY_TAKEDOWN = 70,
	PED_FLAG_DEAD = 71,
	PED_FLAG_IS_SNIPER_SCOPE_ACTIVE = 72,
	PED_FLAG_SUPER_DEAD = 73,
	_PED_FLAG_IS_IN_AIR = 76,
	PED_FLAG_IS_AIMING = 78,
	PED_FLAG_DRUNK = 100,
	_PED_FLAG_IS_NOT_RAGDOLL_AND_NOT_PLAYING_ANIM = 104,
	PED_FLAG_NO_PLAYER_MELEE = 122,
	PED_FLAG_NM_MESSAGE_466 = 125,
	PED_FLAG_INJURED_LIMP = 166,
	PED_FLAG_INJURED_LIMP_2 = 170,
	PED_FLAG_INJURED_DOWN = 187,
	PED_FLAG_SHRINK = 223,
	PED_FLAG_MELEE_COMBAT = 224,
	_PED_FLAG_IS_ON_STAIRS = 253,
	_PED_FLAG_HAS_ONE_LEG_ON_GROUND = 276,
	PED_FLAG_NO_WRITHE = 281,
	PED_FLAG_FREEZE = 292,
	PED_FLAG_IS_STILL = 301,
	PED_FLAG_NO_PED_MELEE = 314,
	_PED_SWITCHING_WEAPON = 331,
	PED_FLAG_ALPHA = 410,
};


enum TraceFlags
{
	IntersectNone = 0,
	IntersectWorld = 1,
	IntersectVehicles = 2,
	IntersectPedsSimpleCollision = 4,
	IntersectPeds = 8,
	IntersectObjects = 16,
	IntersectWater = 32,
	IntersectUnknown = 128,
	IntersectFoliage = 256,
	IntersectEverything = 4294967295
};

namespace DefaultColor
{
	const Color red(255, 0, 0, 255);
	const Color green(0, 255, 0, 255);
	const Color blue(0, 0, 255, 255);
	const Color white(255, 255, 255, 255);
	const Color black(0, 0, 0, 255);
	const Color grey(180, 180, 180, 255);
	const Color yellow(255, 255, 0, 255);
}